- hosts: myhosts
  #INCOMPLETO! A ideia é tentar automatizar o registro de runners via API do gitlab.
  vars_prompt:
    - name: "gitlab_private_token"
      prompt: "token privado do GitLab:"
      private: yes 
    - name: "runner_registration_token"
      prompt: "token de registro do Runner:"
      private: yes

  tasks:
    - name: Verificação - Docker já instalado.
      command: docker --version
      register: docker_version
      ignore_errors: yes
      changed_when: false

    - name: Verificação se runner está registrado!
      stat:
        path: "/runners_registrados.txt"
      register: status_arquivo

    - name: Verificar se já está registrado
      when: status_arquivo.stat.exists
      slurp:
        src: "/runners_registrados.txt"
      register: arquivo_registros

    - name: Registrar runner
      vars:
        arquivo_registros: "{{ lookup('file', '/runners_registrados.txt') }}"
        runner_registrados: "{{ not (arquivo_registros.content | default('') | b64decode | regex_search('token: ' + runner_registration_token)) }}"
      uri:
        url: "http://{{ hostvars['nginx']['domain'] }}/api/v4/runners"
        method: POST
        body_format: json
        body:
          token: "{{ runner_registration_token }}"
          description: "Runner criado via ansible"
          locked: false
        headers:
          Content-Type: "application/json"
          Private-Token: "{{ gitlab_private_token }}"
        status_code: 200
      register: Response_runner
      when: runner_registrados
