
- name: Migração de dados MySQL
  hosts: origem
  tasks:
    - name: Exportar dados do MySQL no host origem
      command: mysqldump -u <USUARIO> -p<SENHA> <BANCO> > /tmp/dados.sql
      register: export_result

- name: Transferência e Importação no Destino
  hosts: destino
  tasks:
    - name: Transferir dump para o host destino
      copy: 
        src: /tmp/dados.sql
        dest: /tmp/dados.sql

    - name: Importar dados no MySQL no host destino
      command: mysql -u <USUARIO> -p<SENHA> <BANCO> < /tmp/dados.sql
      register: import_result

    - name: Verificar tabelas corrompidas no MySQL
      shell: |
        mysqlcheck -u <USUARIO> -p<SENHA> <BANCO> --check --extended > /tmp/mysql_check.log
      register: check_result

    - name: Checar log para erros de corrupção
      command: grep -i 'corrupt' /tmp/mysql_check.log
      register: corrupt_check
      failed_when: corrupt_check.rc == 0
      ignore_errors: yes

    - name: Enviar alerta de tabelas corrompidas (se houver)
      mail:
        to: "seu_email@example.com"
        subject: "Alerta: Tabelas corrompidas após migração"
        body: |
          Algumas tabelas estão corrompidas após a migração:
          {{ corrupt_check.stdout }}
      when: corrupt_check.rc == 0
