# playbook.yml
- name: Configuração de replicação MySQL para standby
  hosts: producao
  become: yes
  tasks:
    - name: Habilitar log binário no servidor producao
      lineinfile:
        path: /etc/mysql/my.cnf
        regexp: '^log_bin'
        line: 'log_bin = /var/log/mysql/mysql-bin.log'
        state: present

    - name: Configurar o ID do servidor producao
      lineinfile:
        path: /etc/mysql/my.cnf
        regexp: '^server-id'
        line: 'server-id = 1'
        state: present

    - name: Reiniciar MySQL no servidor producao
      service:
        name: mysql
        state: restarted

    - name: Criar usuário de replicação no servidor producao
      mysql_user:
        name: "replicador"
        password: "senha_replicacao"
        host: "%"
        priv: "*.*:REPLICATION SLAVE"
        state: present

    - name: Fazer backup do banco de dados producao
      command: "mysqldump -u root -p'SUA_SENHA' --all-databases > /tmp/backup.sql"

    - name: Copiar backup para o servidor standby
      copy:
        src: /tmp/backup.sql
        dest: /tmp/backup.sql
      delegate_to: standby
